### ISSUE TITLE
Can't complete dependencies installation.

### ISSUE THREAD

**Issue by armoucar** [prerender/prerender#109]
I've cloned the project and I'm trying to install the dependencies (`npm install`) to run it.
I've got a problem at the moment the `node-gyp` tries to compile a module called `weak`.

I'm running in a `OS X 10.9`, `node -v: v0.11.13`, `npm -v: 1.4.23` and my command line tools are up to date.

Bellow the stack I got:

```
$ npm install
 
> weak@0.2.2 install /Users/arthur/Dev/workspaces/oss/js/prerender/node_modules/phantom/node_modules/dnode/node_modules/weak
> node-gyp rebuild

  CXX(target) Release/obj.target/weakref/src/weakref.o
../src/weakref.cc:58:10: error: no viable conversion from 'Persistent<v8::Object>' to 'Handle<v8::Object>'
  return cont->target;
         ^~~~~~~~~~~~
/Users/arthur/.node-gyp/0.11.13/deps/v8/include/v8.h:218:26: note: candidate constructor
      (the implicit copy constructor) not viable: no known conversion from 'Persistent<v8::Object>' to
      'const v8::Handle<v8::Object> &' for 1st argument
template <class T> class Handle {
                         ^
/Users/arthur/.node-gyp/0.11.13/deps/v8/include/v8.h:235:32: note: candidate template ignored: could not match
      'Handle' against 'Persistent'
  template <class S> V8_INLINE Handle(Handle<S> that)
                               ^
../src/weakref.cc:69:10: error: no viable conversion from 'Persistent<v8::Array>' to 'Handle<v8::Array>'
  return cont->callbacks;
         ^~~~~~~~~~~~~~~
/Users/arthur/.node-gyp/0.11.13/deps/v8/include/v8.h:218:26: note: candidate constructor
      (the implicit copy constructor) not viable: no known conversion from 'Persistent<v8::Array>' to
      'const v8::Handle<v8::Array> &' for 1st argument
template <class T> class Handle {
                         ^
/Users/arthur/.node-gyp/0.11.13/deps/v8/include/v8.h:235:32: note: candidate template ignored: could not match
      'Handle' against 'Persistent'
  template <class S> V8_INLINE Handle(Handle<S> that)
                               ^
../src/weakref.cc:81:45: error: unknown type name 'AccessorInfo'
                                      const AccessorInfo& info) {
                                            ^
../src/weakref.cc:82:3: error: calling a protected constructor of class 'v8::HandleScope'
  UNWRAP
  ^
../src/weakref.cc:74:15: note: expanded from macro 'UNWRAP'
  HandleScope scope;                      \
              ^
/Users/arthur/.node-gyp/0.11.13/deps/v8/include/v8.h:845:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/weakref.cc:89:45: error: unknown type name 'AccessorInfo'
                                      const AccessorInfo& info) {
                                            ^
../src/weakref.cc:90:3: error: calling a protected constructor of class 'v8::HandleScope'
  UNWRAP
  ^
../src/weakref.cc:74:15: note: expanded from macro 'UNWRAP'
  HandleScope scope;                      \
              ^
/Users/arthur/.node-gyp/0.11.13/deps/v8/include/v8.h:845:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/weakref.cc:97:46: error: unknown type name 'AccessorInfo'
                                       const AccessorInfo& info) {
                                             ^
../src/weakref.cc:98:10: error: calling a protected constructor of class 'v8::HandleScope'
  return HandleScope().Close(Integer::New(None));
         ^
/Users/arthur/.node-gyp/0.11.13/deps/v8/include/v8.h:845:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/weakref.cc:98:24: error: no member named 'Close' in 'v8::HandleScope'
  return HandleScope().Close(Integer::New(None));
         ~~~~~~~~~~~~~ ^
../src/weakref.cc:98:47: error: too few arguments to function call, expected 2, have 1
  return HandleScope().Close(Integer::New(None));
                             ~~~~~~~~~~~~     ^
/Users/arthur/.node-gyp/0.11.13/deps/v8/include/v8.h:2074:3: note: 'New' declared here
  static Local<Integer> New(Isolate* isolate, int32_t value);
  ^
../src/weakref.cc:103:48: error: unknown type name 'AccessorInfo'
                                         const AccessorInfo& info) {
                                               ^
../src/weakref.cc:104:3: error: calling a protected constructor of class 'v8::HandleScope'
  UNWRAP
  ^
../src/weakref.cc:74:15: note: expanded from macro 'UNWRAP'
  HandleScope scope;                      \
              ^
/Users/arthur/.node-gyp/0.11.13/deps/v8/include/v8.h:845:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/weakref.cc:105:53: error: too few arguments to function call, expected 2, have 1
  return Boolean::New(!dead && obj->Delete(property));
         ~~~~~~~~~~~~                               ^
/Users/arthur/.node-gyp/0.11.13/deps/v8/include/v8.h:6129:1: note: 'New' declared here
Handle<Boolean> Boolean::New(Isolate* isolate, bool value) {
^
../src/weakref.cc:110:47: error: unknown type name 'AccessorInfo'
                                        const AccessorInfo& info) {
                                              ^
../src/weakref.cc:111:3: error: calling a protected constructor of class 'v8::HandleScope'
  UNWRAP
  ^
../src/weakref.cc:74:15: note: expanded from macro 'UNWRAP'
  HandleScope scope;                      \
              ^
/Users/arthur/.node-gyp/0.11.13/deps/v8/include/v8.h:845:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/weakref.cc:118:47: error: unknown type name 'AccessorInfo'
                                        const AccessorInfo& info) {
                                              ^
../src/weakref.cc:119:3: error: calling a protected constructor of class 'v8::HandleScope'
  UNWRAP
  ^
../src/weakref.cc:74:15: note: expanded from macro 'UNWRAP'
  HandleScope scope;                      \
              ^
/Users/arthur/.node-gyp/0.11.13/deps/v8/include/v8.h:845:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/weakref.cc:126:48: error: unknown type name 'AccessorInfo'
                                         const AccessorInfo& info) {
                                               ^
../src/weakref.cc:127:10: error: calling a protected constructor of class 'v8::HandleScope'
  return HandleScope().Close(Integer::New(None));
         ^
/Users/arthur/.node-gyp/0.11.13/deps/v8/include/v8.h:845:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/weakref/src/weakref.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/arthur/.nvm/v0.11.13/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1046:12)
gyp ERR! System Darwin 13.3.0
gyp ERR! command "node" "/Users/arthur/.nvm/v0.11.13/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/arthur/Dev/workspaces/oss/js/prerender/node_modules/phantom/node_modules/dnode/node_modules/weak
gyp ERR! node -v v0.11.13
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
npm ERR! weak@0.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the weak@0.2.2 install script.
npm ERR! This is most likely a problem with the weak package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls weak
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.3.0
npm ERR! command "node" "/Users/arthur/.nvm/v0.11.13/bin/npm" "install"
npm ERR! cwd /Users/arthur/Dev/workspaces/oss/js/prerender
npm ERR! node -v v0.11.13
npm ERR! npm -v 1.4.23
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/arthur/Dev/workspaces/oss/js/prerender/npm-debug.log
npm ERR! not ok code 0
```

**Comment by croshim** [comment]
same issue, downgrading didn't help

**Comment by thoop** [comment]
are you on OS X? I'll look into it.

**Comment by croshim** [comment]
Windows

**Comment by armoucar** [comment]
In my case, when I did the downgrade, it has worked. OS X

**Comment by u982744** [comment]
I have the same issue and I am currently using node v0.10.35.

**Comment by croshim** [comment]
Still can't install, even after downgrading to 0.10.28
https://gist.github.com/croshim/4fe19515c1332856ed4e

**Comment by thoop** [comment]
@croshim it looks like it can't find Make?

`Error: not found: make`

**Comment by hades200082** [comment]
Same problem here, downgrading node to 10.x worked but also then had to install Windows Server 2008 SDK and .Net Framework 3.5

**Comment by thoop** [comment]
@hades200082 was it the same issues with node-gyp?

**Comment by hades200082** [comment]
@thoop No.  The node-gyp error I had previously was the undocumented Python dependency.  Upon installing the correct version of Python I was getting the same error as the OP above.  Then, once I downgraded to nodejs 0.10.36 I got the SDK error instead.

I then installed the Windows Server 2008 SDK and .Net Framework 3.5 and tried again and all is well.

I think you need to document these dependencies on https://prerender.io/documentation

* Python 2.x
* For windows servers the appropriate SDK and .NET 3.5
* nodejs 0.10.x

**Comment by thoop** [comment]
Ok, thanks for letting me know about the windows dependencies.

**Comment by JakeFalcor** [comment]
You can temporarily disable weak dependency, by passing `dnodeOpts: { weak: false }` in lib/server.js:93.  
Obviously should not be done in production, since guessing from weak docs it exposes garbage collection APIs which are used by phantom.

**Comment by thoop** [comment]
Everything should work now that we switched to a new phantomjs -> node bridge in Prerender v4.0.3
