### ISSUE TITLE
Error: write EINVAL - cannot write to IPC channel.

### ISSUE THREAD

**Issue by devmondo** [prerender/prerender#150]
hi,

i get this error when i launch on my machine

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EINVAL - cannot write to IPC channel.
    at errnoException (child_process.js:998:11)
    at ChildProcess.target.send (child_process.js:465:16)
    at Worker.send (cluster.js:406:21)
    at sendInternalMessage (cluster.js:399:10)
    at handleResponse (cluster.js:177:5)
    at respond (cluster.js:192:5)
    at Object.messageHandler.queryServer (cluster.js:247:5)
    at handleMessage (cluster.js:197:32)
    at ChildProcess.EventEmitter.emit (events.js:117:20)
    at handleMessage (child_process.js:322:10)
2014-12-22T05:31:00.232Z starting phantom
```

**Comment by geolyth** [comment]
Perhaps you have WAMP active?

**Comment by devmondo** [comment]
@geolyth  i dont use WAMP, but i found out  after searching that this error message means that there is another  process using the port, so i restarted PC and everything is fine, and i suspect it is a conflict between Prerender or phantomjs and BrowserSync.

the thing is, how can i shut down Prerender process if somehow it didn't shut down when you close the console, in other word how do i kill specific Node process completely with a command ?

**Comment by thoop** [comment]
If you are on OSX, you can do `ps aux | grep phantomjs` to see if there are any phantomjs instances still running and kill them using the pid

**Comment by devmondo** [comment]
@thoop thank you, i use Windows, but i found the equivalent command on windows
