### ISSUE TITLE
Error: Cannot find module 'weak'

### ISSUE THREAD

**Issue by soitun** [prerender/prerender#173]
I build pantomjs2 from source , and  excute npm install at  prerender path, everything is go ok,
but when run  node server.js , display flow error 

Error: Cannot find module 'weak'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at new D (/root/prerender/node_modules/phantom/node_modules/dnode/index.js:28:20)
    at module.exports (/root/prerender/node_modules/phantom/node_modules/dnode/index.js:8:12)
    at /root/prerender/node_modules/phantom/phantom.js:159:13
    at Server.handler (/root/prerender/node_modules/phantom/node_modules/shoe/index.js:22:9)
    at Server.emit (events.js:107:17)
    at App.emit (/root/prerender/node_modules/phantom/node_modules/shoe/node_modules/sockjs/lib/sockjs.js:182:27)
2015-04-05T06:46:18.306Z worker 23 died, restarting!
module.js:338
    throw err;
          ^
Error: Cannot find module 'weak'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at new D (/root/prerender/node_modules/phantom/node_modules/dnode/index.js:28:20)
    at module.exports (/root/prerender/node_modules/phantom/node_modules/dnode/index.js:8:12)
    at /root/prerender/node_modules/phantom/phantom.js:159:13
    at Server.handler (/root/prerender/node_modules/phantom/node_modules/shoe/index.js:22:9)
    at Server.emit (events.js:107:17)
    at App.emit (/root/prerender/node_modules/phantom/node_modules/shoe/node_modules/sockjs/lib/sockjs.js:182:27)
2015-04-05T06:46:18.348Z worker 24 died, restarting!
2015-04-05T06:46:18.763Z starting phantom on port [12325]
2015-04-05T06:46:18.799Z Server running on port 3000
2015-04-05T06:46:18.803Z starting phantom on port [12326]
2015-04-05T06:46:18.830Z Server running on port 3000

**Comment by soitun** [comment]
node is unzip at /usr/local/node-v0.12.2-linux-x64/

**Comment by thoop** [comment]
That's some kind of configuration issue not related to Prerender. Did `npm install` install weak?

**Comment by oliver-moran** [comment]
Installed Python and this problem went away:

https://www.python.org/downloads/

**Comment by soitun** [comment]
I have installed python 2.6.6

**Comment by oliver-moran** [comment]
I installed 2.7.9. Closed the command window, deleted the node_modules directory, and did `npm install` again. Then it just worked.

**Comment by soitun** [comment]
thanks to oliver-moran
I   excute " yum -y update " , then  did npm install  again. then it worked .

**Comment by oliver-moran** [comment]
Could add it to the docs that Python is required (and the min version, if known).

**Comment by thoop** [comment]
Thanks, that's probably a good idea

**Comment by graywithanA** [comment]
For anyone who may be trying to install Prerender on a server that has multiple versions of Python installed (such as a WebFaction server) and is getting a version related error when `node-gyp rebuild` tries to run because the default Python version is wrong, try this:

```
$ npm config set python /path/to/executable/python2.7
```

**Comment by thoop** [comment]
Thanks @graywithanA !
