### ISSUE TITLE
getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by nmehra** [prerender/prerender#226]
Hi,

I am trying to run prerender.io on a linux machine where I have installed phantomjs and the git code from https://github.com/prerender/prerender
I was able to execute prerender code on my local windows box but my aws linux instance is giving the following error when I run 
node server.js

2015-08-27T10:54:50.602Z starting worker thread #0
2015-08-27T10:54:50.608Z starting worker thread #1
2015-08-27T10:54:50.836Z starting phantom on port [12301]
2015-08-27T10:54:50.860Z starting phantom on port [12302]

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)

events.js:72
        throw er; // Unhandled 'error' event
              ^
2015-08-27T10:54:50.884Z worker 1 died, restarting!

Can you please guide me as to what this issue might be.

**Comment by thoop** [comment]
Sorry I never responded here. Can you try out latest version of Prerender (v4.0.3) and report back if you still have this issue? I wonder if Prerender wasn't able to bind to those ports or something. Feel free to reopen if the new version of Prerender has this issue as well.
