### ISSUE TITLE
npm install, weak submodule fails with "out of heap space" fatal error C1060

### ISSUE THREAD

**Issue by mararn1618** [prerender/prerender#258]
Dear community,

unfortunately npm install fails with fatal error C1060 for the submodule weak, stating that heap space is exceeded.

I would be grateful if anyone could provide any kind of help.

**My environment is**
* Windows 7 64bit
* Microsoft Visual Studio Express 2012
* Microsoft Windows SDK for Windows 7 (7.1)
* NodeJS v5.2.0
* NPM 3.3.12
* Python 2.7.8

**The console output is**
````
C:\PROJECTS_MARS\prerender\node_modules\weak>if not defined npm_config_node_gyp
(node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_mod
ules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  weakref.cc
C:\PROJECTS_MARS\prerender\node_modules\nan\nan.h(70): fatal error C1060: Kein
verfügbarer Speicher mehr im Heap [C:\PROJECTS_MARS\prerender\node_modules\weak
\build\weakref.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:88:13)
gyp ERR! stack     at ChildProcess.emit (events.js:173:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:201:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\PROJECTS_MARS\prerender\node_modules\weak
gyp ERR! node -v v5.2.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:weak@1.0.0 weak@1.0.0 install: `node-gyp rebuild`
npm WARN install:weak@1.0.0 Exit status 1
npm WARN EPACKAGEJSON prerender@3.22.1 No license field.
````

**Comment by thoop** [comment]
This is an issue for weak or node-gyp, not prerender. I don't know if they support Node v5.2 yet.
