### ISSUE TITLE
Issue while running pre render local Ubuntu Rails

### ISSUE THREAD

**Issue by sanyam-j** [prerender/prerender#262]
2016-01-15T05:15:11.266Z Server running on port 3000
module.js:328
    throw err;
    ^

Error: Cannot find module 'weak'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at new D (/home/vm/Desktop/prerender/node_modules/dnode/index.js:28:20)
    at module.exports (/home/vm/Desktop/prerender/node_modules/dnode/index.js:8:12)
    at /home/vm/Desktop/prerender/node_modules/phantom/phantom.js:159:13
    at Server.handler (/home/vm/Desktop/prerender/node_modules/shoe/index.js:22:9)
    at emitOne (events.js:77:13)
    at Server.emit (events.js:169:7)

**Comment by thoop** [comment]
Were there any issues when you ran `npm install`?

**Comment by sanyam-j** [comment]
Yes, i had the error with npm install. Now its working.
