### ISSUE TITLE
Issue while runnning Prerender

### ISSUE THREAD

**Issue by ankitkl** [prerender/prerender#283]
/home/ec2-user/prerender4.0.3/prerender/node_modules/phridge/lib/lift.js:14
        return new Promise(function (resolve, reject) {
                   ^
ReferenceError: Promise is not defined
    at /home/ec2-user/prerender4.0.3/prerender/node_modules/phridge/lib/lift.js:14:20
    at Object.spawn (/home/ec2-user/prerender4.0.3/prerender/node_modules/phridge/lib/spawn.js:45:12)
    at Object.server.createPhantom (/home/ec2-user/prerender4.0.3/prerender/lib/server.js:86:13)
    at Object.server.start (/home/ec2-user/prerender4.0.3/prerender/lib/server.js:36:14)
    at Object.<anonymous> (/home/ec2-user/prerender4.0.3/prerender/server.js:20:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
2016-02-16T07:00:35.242Z worker 17 died, restarting!
2016-02-16T07:00:35.334Z starting phantom...

/home/ec2-user/prerender4.0.3/prerender/node_modules/phridge/lib/lift.js:14
        return new Promise(function (resolve, reject) {

**Comment by ankitkl** [comment]
Need to upgrade the nodejs version... 
Now working fine
