### ISSUE TITLE
Headers with multiple values cause TypeError

### ISSUE THREAD

**Issue by anajavi** [prerender/prerender#287]
I have a server that sets multiple cookies on response. PhantomJS then merges these header values with newline between them.

This causes "TypeError: The header content contains invalid characters" when prerender sets response headers as newline is forbidden character on header value.

Relevant code on prerender:
https://github.com/prerender/prerender/blob/8053332afab16059f3f4d93114ef2c4e71dad5e3/lib/server.js#L455-L459

The underlying cause seems to be in qt. The phantomjs creates header object:
https://github.com/ariya/phantomjs/blob/3d9a327df3c600e90511eabe756b0d340a0d0f6a/src/networkaccessmanager.cpp#L521-L532

And qtnetworkreply api says:
"Returns a list of headers fields that were sent by the remote server, in the order that they were sent. Duplicate headers are merged together and take place of the latter duplicate."

https://doc.qt.io/qt-5.5/qnetworkreply.html#rawHeaderList

I wrote quick hack by try..catching around setHeader which is ugly, but works for now.

**Comment by thoop** [comment]
Do you have a public URL where I can reproduce this myself? Feel free to email me the URL if you don't want to post it here. todd@prerender.io

**Comment by thoop** [comment]
Thanks so much. I'll push the fix for this today and follow up here once done.

**Comment by anajavi** [comment]
Great! Thank you.

**Comment by thoop** [comment]
published in v4.0.4

**Comment by ifeltsweet** [comment]
Was [this commit](https://github.com/prerender/prerender/commit/dac253baf476746694f37d467c0c7c0c7a2b7df9) trying to fix this issue? If so, then it was not fixed, it simply prevented a crash.

This happens because when origin server responds with multiple values of the same header they are concatenated using a newline character inside `req.prerender.headers` (I'm not sure who does the concat, express middleware or prerender). Attempting to set these headers on a response from prerender using `res.setHeader(header, req.prerender.headers[header]);` errors out because of the newline character. A correct strategy here is to split `req.prerender.headers` value on newline character and set each header separately using `res.setHeader()`.

Set-Cookie is an example of one such header that often contains multiple values. So you will see a response from server such as:

```
Set-Cookie: XSRF-TOKEN=abc; expires=Sat, 04-May-2019 11:35:34 GMT; Max-Age=2592000; path=/
Set-Cookie: user=123; expires=Tue, 02-Apr-2024 11:35:33 GMT; Max-Age=157679999; path=/; httponly
Set-Cookie: session=abcdcd; expires=Thu, 04-Apr-2019 13:35:34 GMT; Max-Age=7200; path=/; httponly
```

**Comment by thoop** [comment]
Right, that was just meant to prevent a crash but is probably something we should fix. I'll reopen the issue.

**Comment by abarke** [comment]
Im definitely getting the same issue here:

```
2020-03-23T14:42:07.571302Z app[web.1]: 2020-03-23T14:42:07.570Z getting https://internal.host
2020-03-23T14:42:07.576726Z app[web.1]: _http_outgoing.js:529
2020-03-23T14:42:07.576791Z app[web.1]:     throw new ERR_INVALID_CHAR('header content', name);
2020-03-23T14:42:07.576802Z app[web.1]:     ^
2020-03-23T14:42:07.576813Z app[web.1]: 
2020-03-23T14:42:07.576823Z app[web.1]: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Set-Cookie"]
2020-03-23T14:42:07.576831Z app[web.1]:     at ServerResponse.setHeader (_http_outgoing.js:538:3)
2020-03-23T14:42:07.576846Z app[web.1]:     at Object.newRes.setHeader (/app/lib/server.js:321:8)
```
On localhost (Windows) I seem to only get a warning:
```
warning: unable to set header: Set-Cookie
```
Any chance of a fix?

**Comment by abarke** [comment]
I narrowed the error down to the Set-Cookie cookie being declared twice in the headers. Here is the raw response from the server using Fiddler:
```
Set-Cookie: WEB1=xxxxxx; expires=Mon, 23-Mar-2020 17:59:40 GMT; Max-Age=3600; path=/; secure; HttpOnly; SameSite=lax
Set-Cookie: WEB2=xxxxxx; Path=/
```

If I log the 'Set-Cookie' header value it is interpreted as the following with a CRLF after the first cookie:
```
WEB1=xxxxxx; expires=Mon, 23-Mar-2020 17:47:10 GMT; Max-Age=3600; path=/; secure; HttpOnly; SameSite=lax
WEB2=xxxxxx; Path=/
```
The CRLF leads to the error occuring: `throw new ERR_INVALID_CHAR('header content', name);`

**Comment by abarke** [comment]
I created a fix that replaces a new line with a comma. According to RFC 2109 it's a valid patch, however since RFC 6265 it is no longer endorced... 

_"Origin servers SHOULD NOT fold multiple Set-Cookie header fields into a single header field."_ 

Ref: https://stackoverflow.com/a/2880070/11475075
