### ISSUE TITLE
"Write after end" error

### ISSUE THREAD

**Issue by nottix** [prerender/prerender#292]
Hi,

i'm using prerender (version 1.3.0) on my NodeJS+Express app, and i have this crash after some requests:
`events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write after end
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:413:15)
    at ServerResponse.res.write (/home/scx-page/app/node_modules/compression/index.js:95:17)
    at ServerResponse.res.end (/home/scx-page/app/node_modules/compression/index.js:112:14)
    at ServerResponse.send (/home/scx-page/app/node_modules/express/lib/response.js:191:8)
    at fn (/home/scx-page/app/node_modules/express/lib/response.js:896:10)
    at Function.exports.swig.render (/home/scx-page/app/node_modules/consolidate/lib/consolidate.js:247:5)
    at /home/scx-page/app/node_modules/consolidate/lib/consolidate.js:146:25
    at /home/scx-page/app/node_modules/consolidate/lib/consolidate.js:99:5
    at fs.js:334:14
    at FSReqWrap.oncomplete (fs.js:95:15)`

To reproduce this bug:
1. Open www.mydomain.com/test?_escaped_fragment_=
2. The node app crash.

Without prerender it works correctly.

Thank you.

**Comment by thoop** [comment]
Can you try upgrading to the latest version of Prerender? That's a really old version.

**Comment by nottix** [comment]
@thoop it's true, the latest version fixes the bug. Thank you.

**Comment by nottix** [comment]
hi @thoop, i have deeply tested the latest version "2.2.0" and i found that it's affected by the same bug reported. 

Thank you.

**Comment by nottix** [comment]
I fixed the bug updating Express framework.

**Comment by thoop** [comment]
The latest version of Prerender as of writing this is 4.0.5. Glad you fixed it by upgrading Express!
