### ISSUE TITLE
Cannot read property 'pid' of null

### ISSUE THREAD

**Issue by ChrisZieba** [prerender/prerender#342]
I'm seeing this error happen everytime Phantom crashes. I tossed a return on this [line](https://github.com/prerender/prerender/blob/master/lib/server.js#L613) to try and prevent, which seems like it's working but it's obviously not a solution.

```
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
{ action: 'ping' }
2016-08-24T18:22:50.335Z phantom crashed, restarting...
Bugsnag:  TypeError: Cannot read property 'pid' of null
    at Object.server._disposeAll (/var/app/current/node_modules/prerender/lib/server.js:620:47)
    at .<anonymous> (/var/app/current/node_modules/prerender/lib/server.js:110:15)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at Phantom._onUnexpectedError (/var/app/current/node_modules/phridge/lib/Phantom.js:392:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:122:9)
```

```js
var server = prerender({
  workers: os.cpus().length,
  iterations: 30,
  softIterations: 5,
  cookiesEnabled: false,
  resourceDownloadTimeout: 5000,
  evaluateJavascriptCheckTimeout: 300,
  waitAfterLastRequest: 2000,
  pageDoneCheckTimeout: 500,
  noJsExecutionTimeout: 2000
});
```

**Comment by thoop** [comment]
Ah, I think instead of a return statement, we should probably just call the callback and return. That way a new phantomjs instance would get created.

**Comment by thoop** [comment]
Made a change and testing it. I'll push a new version today.

**Comment by ChrisZieba** [comment]
Nice, thanks for looking into this so quickly!

**Comment by thoop** [comment]
Can you try 4.3.1? Should be fixed!

**Comment by ChrisZieba** [comment]
Seems like this fixed it, thanks!
