### ISSUE TITLE
Error: Module version mismatch. Expected 46, got 47

### ISSUE THREAD

**Issue by shivamindalkar** [prerender/prerender#362]
Error: Module version mismatch. Expected 46, got 47.
  at Error (native)
  at Object.Module._extensions..node (module.js:435:18)

**Comment by thoop** [comment]
Can you give some more info here?

Which version of node are you using?
Which version of Prerender are you using?

Did you see any errors when running `npm install`?

**Comment by shivamindalkar** [comment]
node version4.2..6
npm version3.5.2

Not seen any error its just gives that the error loag as follows



Error: Module version mismatch. Expected 46, got 47.
  at Error (native)
  at Object.Module._extensions..node (module.js:435:18)
  at Module.load
(/home/hp/tnex/pollinate-v4/ui/tasks/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:301:12)
  at Module.require (module.js:354:17)
  at require (internal/module.js:12:17)
  at bindings
(/home/hp/tnex/pollinate-v4/ui/tasks/node_modules/bindings/bindings.js:76:44)
  at Object.<anonymous>
(/home/hp/tnex/pollinate-v4/ui/tasks/node_modules/libxmljs/lib/bindings.js:1:99)
  at Module._compile (module.js:410:26)
  at Object.Module._extensions..js (module.js:417:10)
  at Module.load
(/home/hp/tnex/pollinate-v4/ui/tasks/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:301:12)
  at Module.require (module.js:354:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous>
(/home/hp/tnex/pollinate-v4/ui/tasks/node_modules/libxmljs/index.js:4:16)
  at Module._compile (module.js:410:26)
  at Object.Module._extensions..js (module.js:417:10)
  at Module.load
(/home/hp/tnex/pollinate-v4/ui/tasks/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:301:12)
  at Module.require (module.js:354:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous>
(/home/hp/tnex/pollinate-v4/ui/tasks/node_modules/gulp-xml-editor/index.js:3:19)
  at Module._compile (module.js:410:26)
  at Object.Module._extensions..js (module.js:417:10)
  at Module.load
(/home/hp/tnex/pollinate-v4/ui/tasks/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:301:12)
  at Module.require (module.js:354:17)
  at require (internal/module.js:12:17)
  at requireFn
(/home/hp/tnex/pollinate-v4/ui/tasks/node_modules/gulp-load-plugins/index.js:47:14)
  at Object.defineProperty.get
(/home/hp/tnex/pollinate-v4/ui/tasks/node_modules/gulp-load-plugins/index.js:84:18)
  at Gulp.<anonymous>
(/home/hp/tnex/pollinate-v4/ui/tasks/subtasks/prepareNative.coffee:16:16)
  at module.exports
(/home/hp/tnex/pollinate-v4/ui/tasks/node_modules/orchestrator/lib/runTask.js:34:7)
  at Gulp.Orchestrator._runTask
(/home/hp/tnex/pollinate-v4/ui/tasks/node_modules/orchestrator/index.js:273:3)
  at Gulp.Orchestrator._runStep
(/home/hp/tnex/pollinate-v4/ui/tasks/node_modules/orchestrator/index.js:214:10)
  at Gulp.Orchestrator.start
(/home/hp/tnex/pollinate-v4/ui/tasks/node_modules/orchestrator/index.js:134:8)
  at
/home/hp/tnex/pollinate-v4/ui/tasks/node_modules/gulp/bin/gulp.js:129:20
  at nextTickCallbackWith0Args (node.js:419:9)
  at process._tickCallback (node.js:348:13)
  at Function.Module.runMain (module.js:444:11)
  at startup (node.js:136:18)
  at node.js:966:3

**Comment by thoop** [comment]
I don't see anything about Prerender in that log. What command are you running there?

**Comment by shivamindalkar** [comment]
rvm use 2.3.0

ruby pollinate serve ui

**Comment by thoop** [comment]
I don't think that has anything to do with Prerender. Are you using Prerender?
