### ISSUE TITLE
not running on ubuntu  

### ISSUE THREAD

**Issue by satya5561** [prerender/prerender#370]
/var/www/html/prerender/node_modules/phridge/lib/lift.js:14
        return new Promise(function (resolve, reject) {
                   ^
ReferenceError: Promise is not defined
    at /var/www/html/prerender/node_modules/phridge/lib/lift.js:14:20
    at Object.spawn (/var/www/html/prerender/node_modules/phridge/lib/spawn.js:45:12)
    at Object.server.createPhantom (/var/www/html/prerender/lib/server.js:88:13)
    at Object.server.start (/var/www/html/prerender/lib/server.js:38:14)
    at Object.<anonymous> (/var/www/html/prerender/server.js:20:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
2017-01-06T07:40:18.578Z worker 64 died, restarting!
2017-01-06T07:40:18.724Z starting phantom...
2017-01-06T07:40:18.727Z Terminating worker #65

/var/www/html/prerender/node_modules/phridge/lib/lift.js:14
        return new Promise(function (resolve, reject) {
                   ^
ReferenceError: Promise is not defined
    at /var/www/html/prerender/node_modules/phridge/lib/lift.js:14:20
    at Object.spawn (/var/www/html/prerender/node_modules/phridge/lib/spawn.js:45:12)
    at Object.server.createPhantom (/var/www/html/prerender/lib/server.js:88:13)
    at Object.server.start (/var/www/html/prerender/lib/server.js:38:14)
    at Object.<anonymous> (/var/www/html/prerender/server.js:20:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
2017-01-06T07:40:18.735Z worker 65 died, restarting!
2017-01-06T07:40:18.756Z starting phantom...
2017-01-06T07:40:18.759Z Terminating worker #66

**Comment by thoop** [comment]
PhantomJS does not yet support the global Promise added in ES6. You'll need to include a polyfill for browsers that do not support Promise. Once PhantomJS supports ES6, then this error will go away.
