### ISSUE TITLE
How to custom plugin 

### ISSUE THREAD

**Issue by mhf-ir** [prerender/prerender#400]
Here my code:
```
// customPlugin.js
// customPlugin for modifyHtml
module.exports = {
    beforeSend: function(req, res, next) {
      req.prerender.documentHTML = req.prerender.documentHTML.toString().replace(/foo/, 'bar');
      next();
  },
};
```
And my server:
```
const customPlugin = require('./customPlugin.js');
const prerender = require('prerender');

const server = prerender({
  port: 5000,
});
server.use(prerender.sendPrerenderHeader());
server.use(prerender.removeScriptTags());
server.use(prerender.httpHeaders());
server.use(customPlugin());
server.start();
```

And it's give me an error:
```
server.use(customPlugin());
           ^

TypeError: customPlugin is not a function
    at Object.<anonymous> (prerender.js:10:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3
```

**Comment by thoop** [comment]
Since your `module.exports` is already an object, you can just do:

`server.use(customPlugin);`

The reason we call those as a function is just how they get added to the `prerender` object.
