### ISSUE TITLE
Calling prerender.exit() throws an error

### ISSUE THREAD

**Issue by GreenGremlin** [prerender/prerender#406]
It appears prerener is trying to kill a process that has already ended.

Also, wrapping `prerender.exit()` in a try/catch doesn't catch the error, so I assume it must be thrown from a child process.

Error call stack:

```
Error: kill ESRCH
    at exports._errnoException (util.js:1018:11)
    at process.kill (internal/process.js:190:13)
    at EventEmitter.<anonymous> (/Users/jonathan/code/github/prerender/lib/index.js:49:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
    at ChildProcess.<anonymous> (cluster.js:379:15)
    at ChildProcess.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

I'm running Node v6.10.1.

**Comment by thoop** [comment]
I'll have to look into this more. Thanks for the heads up. Which operating system are you using? From your stack there it looks like OSX but want to make sure.

**Comment by GreenGremlin** [comment]
Yes, I'm on OS X 10.12.5

**Comment by thoop** [comment]
Our latest version of Prerender shouldn't have this issue anymore. Please upgrade and feel free to reopen if you run into any similar issues here.

**Comment by GreenGremlin** [comment]
Looks good, thanks!
