### ISSUE TITLE
Got SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by vIceBerg** [prerender/prerender#434]
Hi!

I have a website which returns a lot of data. The Prerender server crashes with this message:

SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at Phantom._receive (/home/ubuntu/prerender/node_modules/phridge/lib/Phantom.js:247:20)
    at emitOne (events.js:96:13)
    at CropPhridgePrefix.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at CropPhridgePrefix.Readable.push (_stream_readable.js:134:10)
    at CropPhridgePrefix.Transform.push (_stream_transform.js:128:32)
    at CropPhridgePrefix._transform (/home/ubuntu/prerender/node_modules/phridge/lib/forkStdout.js:85:10)
    at CropPhridgePrefix.Transform._read (_stream_transform.js:167:10)
    at CropPhridgePrefix.Transform._write (_stream_transform.js:155:12)
internal/process.js:190
      throw errnoException(err, 'kill');
      ^

Error: kill ESRCH
    at exports._errnoException (util.js:1020:11)
    at process.kill (internal/process.js:190:13)
    at EventEmitter.<anonymous> (/home/ubuntu/prerender/lib/index.js:39:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
    at ChildProcess.<anonymous> (cluster.js:378:15)
    at ChildProcess.g (events.js:292:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

The data returned looks like this:
{"status":"success","id":116,"data":{"resourcesRequested":[{"headers":[{"name":"Accept","value":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"},{"name":"User-Agent","value":"Mozilla/5.0 (Unknown; Linux x86_64) AppleWeb
Kit/538.1 (KHTML, like Gecko) PhantomJS/2.1.1 Safari/538.1 Prerender (+https://github.com/prerender/prerender)"},{"name":"X-Prerender","value":"1"}],"id":1,"method":"GET","time":"2017-09-28T17:38:57.293Z","url":"https://****.****.com/index.html"},{"headers":[{"name":"Accept","value":"text/css,*/*;q=0.1"},{"name":"Referer","value":"https://****.****.com/index.html"},{"name":"User-Agent","value":"Mozilla/5.0 (Unknown; Linux x86_64) AppleW
ebKit/538.1 (KHTML, like Gecko) PhantomJS/2.1.1 Safari/538.1 Prerender (+https://github.com/prerender/prerender)"},{"name":"X-Prerender","value":"1"}],"id":2,"method":"GET","time":"2017-09-28T17:38:57.363Z","url":"https://fast.fonts.net/
cssapi/fbaf96e9-eb61-4e30-b35b-73b5cc3537a6.css"},{"headers":[

The data is truncated when the method is called...

My project is a fork of the master branch... So I'm up to date with the lastest sources.

Any idea of how to correct that?

Thanks

**Comment by thoop** [comment]
Whoa that's really weird. I've never seen that and I'm not sure why the response would be truncated. Are you running out of RAM or disk space or anything on your servers? PhantomJS has a memory leak and needs to be restarted often.

Can you try the `chrome` branch of this repo? We've found Chrome to be much more reliable when rendering pages.

**Comment by vIceBerg** [comment]
Hi!

I don`t get out of memory... I checked the process on my linux box using HTop and it takes some memory but not all.

I`ll try the chrome branch right now and get back to you.

**Comment by vIceBerg** [comment]
Is there a quick way to implement the InMemoryCache plug-in? I really need this in order to test properly the chrome branch

**Comment by thoop** [comment]
You should be able to copy it over and just change the names of the plugin functions according to the readme:

```js
var cacheManager = require('cache-manager');

module.exports = {
    init: function() {
        this.cache = cacheManager.caching({
            store: 'memory', max: process.env.CACHE_MAXSIZE || 100, ttl: process.env.CACHE_TTL || 60/*seconds*/
        });
    },

    requestReceived: function(req, res, next) {
        this.cache.get(req.prerender.url, function (err, result) {
            if (!err && result) {
                res.send(200, result);
            } else {
                next();
            }
        });
    },

    pageLoaded: function(req, res, next) {
        this.cache.set(req.prerender.url, req.prerender.documentHTML);
        next();
    }
}
```

We'll be pushing a breaking change there soon where `req.prerender.documentHTML` will be renamed to `req.prerender.content`. Don't forget to npm install `cache-manager` if needed.
