### ISSUE TITLE
SyntaxError: Unexpected token # in JSON at position 0

### ISSUE THREAD

**Issue by shaun-ba** [prerender/prerender#496]
Running latest version

```
0|server   | SyntaxError: Unexpected token # in JSON at position 0
0|server   |     at JSON.parse (<anonymous>)
0|server   |     at createStrictSyntaxError (/home/backend/prerender/node_modules/body-parser/lib/types/json.js:157:10)
0|server   |     at parse (/home/backend/prerender/node_modules/body-parser/lib/types/json.js:83:15)
0|server   |     at /home/backend/prerender/node_modules/body-parser/lib/read.js:121:18
0|server   |     at invokeCallback (/home/backend/prerender/node_modules/raw-body/index.js:224:16)
0|server   |     at done (/home/backend/prerender/node_modules/raw-body/index.js:213:7)
0|server   |     at IncomingMessage.onEnd (/home/backend/prerender/node_modules/raw-body/index.js:273:7)
0|server   |     at emitNone (events.js:86:13)
0|server   |     at IncomingMessage.emit (events.js:188:7)
0|server   |     at endReadableNT (_stream_readable.js:975:12)
```

**Comment by thoop** [comment]
I haven't seen this before. Do you have any way to reproduce this?

**Comment by shaun-ba** [comment]
I don't and annoyingly I'm using PM2 to run prerender server and it seems by default timestamps aren't added to ERROR logs, but are for the running ones. This one was from the ERROR logs so means it crashed the server.

I'll find a way to add timestamps and report back if it's reoccurring.

**Comment by thoop** [comment]
Thanks! I see body-parser in that stack trace, which is only used when the Prerender server receives a `POST` request: https://github.com/prerender/prerender/blob/master/lib/index.js#L24

I'm wondering if you're sending an invalid body there since we expect JSON. We might need to add a try/catch there and return a status code 400 on error.

**Comment by thoop** [comment]
Were you able to figure this out? It definitely seems like an invalid `POST` request to the Prerender server from that stack trace. Feel free to reopen if it was something else.

**Comment by IuryAlves** [comment]
@thoop 

I am having the same problem. Is there some way to disable `post` requests? I only use `get` anyway.

**Comment by thoop** [comment]
You could try removing this line: https://github.com/prerender/prerender/blob/master/lib/index.js#L24
