### ISSUE TITLE
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection

### ISSUE THREAD

**Issue by shaun-ba** [prerender/prerender#497]
Running latest version

```
0|server   | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
0|server   | TypeError: Cannot read property 'kill' of undefined
0|server   |     at Object.chrome.kill (/home/backend/prerender/lib/browsers/chrome.js:39:18)
0|server   |     at Object.server.killBrowser (/home/backend/prerender/lib/server.js:98:15)
0|server   |     at spawnBrowser.then.then.catch (/home/backend/prerender/lib/server.js:79:9)
0|server   |     at runMicrotasksCallback (internal/process/next_tick.js:64:5)
0|server   |     at _combinedTickCallback (internal/process/next_tick.js:73:7)
0|server   |     at process._tickDomainCallback (internal/process/next_tick.js:128:9)
0|server   |     at Module.runMain (module.js:607:11)
0|server   |     at run (bootstrap_node.js:427:7)
0|server   |     at startup (bootstrap_node.js:151:9)
0|server   |     at bootstrap_node.js:542:3
```

**Comment by thoop** [comment]
I think https://github.com/prerender/prerender/pull/493 should prevent this error but any info you can provide on reproducing this would help verify that the error you posted isn't just a symptom of a larger issue with the browser crashing and not being found or something.

**Comment by shaun-ba** [comment]
Thanks i'll keep an eye out as with the other issues i posted. 

Can you explain how I would provide a method to reproduce though? It's not like any of my code is running here, so it's just pointing to a domain and that's it

**Comment by thoop** [comment]
Yeah like if you had a specific URL that was able to reproduce this error. That way we could try to figure out what caused `this.chromeChild` to be undefined in that error case.
