### ISSUE TITLE
all turn 504 after "error closing Chrome tab Error: not opened"

### ISSUE THREAD

**Issue by chongwang87** [prerender/prerender#499]
meteorjs 1.6.1
prerender-node 3.1.1
prerender 5.3.1
Chrome: HeadlessChrome/65.0.3325.181
ubuntu 16

2018-03-23T15:10:56.270Z error closing Chrome tab Error: not opened
    at WebSocket.send (/www/lib/prerender/node_modules/ws/lib/WebSocket.js:355:18)
    at Chrome.enqueueCommand (/www/lib/prerender/node_modules/chrome-remote-interface/lib/chrome.js:124:16)
    at /www/lib/prerender/node_modules/chrome-remote-interface/lib/chrome.js:86:28
    at new Promise (<anonymous>)
    at Chrome.send (/www/lib/prerender/node_modules/chrome-remote-interface/lib/chrome.js:85:16)
    at Object.handler [as closeTarget] (/www/lib/prerender/node_modules/chrome-remote-interface/lib/api.js:32:23)
    at Promise (/www/lib/prerender/lib/browsers/chrome.js:146:22)
    at new Promise (<anonymous>)
    at Object.chrome.closeTab (/www/lib/prerender/lib/browsers/chrome.js:144:9)
    at Object.server.finish (/www/lib/prerender/lib/server.js:274:16)

2018-03-23T15:10:56.668Z getting https://www.keepital.com/company/sg/miryoku-bistro-pte-ltd
2018-03-23T15:10:56.672Z Error: unexpected server response (404)
    at ClientRequest._req.on (/www/lib/prerender/node_modules/ws/lib/WebSocket.js:651:26)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at Socket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
2018-03-23T15:10:56.673Z got 504 in 5ms for https://www.keepital.com/company/sg/miryoku-bistro-pte-ltd

2018-03-23T15:11:06.910Z getting https://www.keepital.com/company/sg/streavr-pte-ltd
2018-03-23T15:11:06.915Z Error: unexpected server response (404)
    at ClientRequest._req.on (/www/lib/prerender/node_modules/ws/lib/WebSocket.js:651:26)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at Socket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
2018-03-23T15:11:06.916Z got 504 in 6ms for https://www.keepital.com/company/sg/streavr-pte-ltd

**Comment by thoop** [comment]
I don't think running two instances of the Prerender server is a good idea since it's going to try to start two versions of Chrome on the same port for the websocket connection. I'd try to stick with 1 Prerender server running per machine.

**Comment by thoop** [comment]
Going to close this issue since it looks like the 2 instances of Chrome would cause this. You should only run 1 instance of the Prerender server and Chrome will start the tabs in different processes to scale with multi-cpu environments.

**Comment by chongwang87** [comment]
we use 1 instance for our core website with millions of pages and another instance for the rest of the websites (about 150 websites)

i remember when i implemented prerender in my server (quite sometime ago with PhantomJS), there is a limitation for each instance (something related to number of workers & iterations). that's the reason why we setup 2 instance to balance out the requests & render (1 for major website & another 1 for the rest of the website).

if i do it wrongly, can you please advise what's the best way to maximise the prerender to accept and render as many request as possible, and also we can balance out 50% request for major website and 50% for the rest of the websites.

thanks in advance

**Comment by thoop** [comment]
If you need them to be two separate Prerender servers, I'd suggest running them on different machines. If that's not necessary, try running one server and see if it can handle the load for both websites.
