### ISSUE TITLE
Unhandled Rejection: Security.setOverrideCertificateErrors

### ISSUE THREAD

**Issue by srossross-tableau** [prerender/prerender#520]
I'm getting this error in the logs, any idea what I am doing wrong?

```Unhandled Rejection at: Promise {
  <rejected> { Error: 'Security.setOverrideCertificateErrors' wasn't found
    at /app/node_modules/chrome-remote-interface/lib/chrome.js:90:30
    at Chrome.handleMessage (/app/node_modules/chrome-remote-interface/lib/chrome.js:289:13)
    at WebSocket.<anonymous> (/app/node_modules/chrome-remote-interface/lib/chrome.js:266:27)
    at WebSocket.emit (events.js:159:13)
    at Receiver._receiver.onmessage (/app/node_modules/ws/lib/WebSocket.js:143:54)
    at Receiver.dataMessage (/app/node_modules/ws/lib/Receiver.js:385:14)
    at extension.decompress (/app/node_modules/ws/lib/Receiver.js:354:40)
    at _inflate.flush (/app/node_modules/ws/lib/PerMessageDeflate.js:279:12)
    at afterWrite (_stream_writable.js:455:3)
    at onwrite (_stream_writable.js:446:7)
  response: 
   { code: -32601,
     message: '\'Security.setOverrideCertificateErrors\' wasn\'t found' } },
  __NR_context: 
   { parentIdx: -1,
     idx: 0,
     context: { segments: [Array] },
     child: null } } reason: { Error: 'Security.setOverrideCertificateErrors' wasn't found
    at /app/node_modules/chrome-remote-interface/lib/chrome.js:90:30
    at Chrome.handleMessage (/app/node_modules/chrome-remote-interface/lib/chrome.js:289:13)
    at WebSocket.<anonymous> (/app/node_modules/chrome-remote-interface/lib/chrome.js:266:27)
    at WebSocket.emit (events.js:159:13)
    at Receiver._receiver.onmessage (/app/node_modules/ws/lib/WebSocket.js:143:54)
    at Receiver.dataMessage (/app/node_modules/ws/lib/Receiver.js:385:14)
    at extension.decompress (/app/node_modules/ws/lib/Receiver.js:354:40)
    at _inflate.flush (/app/node_modules/ws/lib/PerMessageDeflate.js:279:12)
    at afterWrite (_stream_writable.js:455:3)
    at onwrite (_stream_writable.js:446:7)
  response: 
   { code: -32601,
     message: '\'Security.setOverrideCertificateErrors\' wasn\'t found' } }
```

**Comment by thoop** [comment]
Hmm, which version of Prerender are you using and which version of Chrome are you using? Can you remove your node_modules folder and run `npm install` again and see if that changes anything?
