### ISSUE TITLE
The occasional mistake of 504

### ISSUE THREAD

**Issue by lican09** [prerender/prerender#524]
I start a server in docker container, sometimes works fine. But sometimes result 504.
HeadlessChrome version 67.0.3396.79
node server.js of master branch code
error log print as follows:
> 2018-06-29T02:32:40.577Z Started Chrome: HeadlessChrome/67.0.3396.79
> 2018-06-29T02:32:59.652Z getting http://www.gamersky.com/
> 2018-06-29T02:33:16.590Z capture screenshot timed out for http://www.gamersky.com/
> 2018-06-29T02:33:16.630Z got 504 in 16978ms for http://www.gamersky.com/
> 2018-06-29T02:34:03.873Z getting http://www.gamersky.com/
> 2018-06-29T02:34:19.509Z capture screenshot timed out for http://www.gamersky.com/
> 2018-06-29T02:34:19.511Z got 504 in 15638ms for http://www.gamersky.com/
> 2018-06-29T02:35:06.833Z getting http://www.gamersky.com/
> 2018-06-29T02:35:23.078Z capture screenshot timed out for http://www.gamersky.com/
> 2018-06-29T02:35:23.079Z got 504 in 16246ms for http://www.gamersky.com/

The strange thing is that, it works fine on my computer when not use docker container.
I try to modify the PAGE_LOAD_TIMEOUT,but no effect!
Is there some optimizations to do?thanks!

**Comment by thoop** [comment]
What kind of CPU/RAM does your server have available? Sometimes this can happen if you run out of RAM. It looks like your requests are pretty spread out so it doesn't look to be a load issue.

Are you seeing Chrome crash before you see those 504s? Does it fix itself after a certain number of requests?

**Comment by lican09** [comment]
cpu info: Intel(R) Xeon(R) CPU E5-26xx v4
cores: 2
I looked cpu loading too high. Maybe the bottleneck is cpu.

**Comment by lican09** [comment]
2018-07-03T10:04:38.417Z got 504 in 3ms for http://www.watertu.com/
2018-07-03T10:04:38.423Z getting http://www.gusuwang.com/
2018-07-03T10:04:38.426Z { Error: connect ECONNREFUSED 127.0.0.1:9222
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1158:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9222 }
2018-07-03T10:04:38.426Z got 504 in 3ms for http://www.gusuwang.com/
2018-07-03T10:04:38.431Z getting http://www.gusuwang.com/
2018-07-03T10:04:38.435Z { Error: connect ECONNREFUSED 127.0.0.1:9222
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1158:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9222 }
2018-07-03T10:04:38.436Z got 504 in 5ms for http://www.gusuwang.com/
2018-07-03T10:04:38.442Z getting http://www.gusuwang.com/
2018-07-03T10:04:38.446Z { Error: connect ECONNREFUSED 127.0.0.1:9222
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1158:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9222 }
2018-07-03T10:04:38.446Z got 504 in 4ms for http://www.gusuwang.com/
2018-07-03T10:04:38.452Z getting http://www.lanin.net/
2018-07-03T10:04:38.455Z { Error: connect ECONNREFUSED 127.0.0.1:9222
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1158:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9222 }
2018-07-03T10:04:38.455Z got 504 in 3ms for http://www.lanin.net/
2018-07-03T10:04:38.462Z getting http://www.lanin.net/
2018-07-03T10:04:38.465Z { Error: connect ECONNREFUSED 127.0.0.1:9222
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1158:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9222 }
2018-07-03T10:04:38.465Z got 504 in 3ms for http://www.lanin.net/
2018-07-03T10:04:38.468Z Chrome connection closed... restarting Chrome
2018-07-03T10:04:38.469Z Starting Chrome
2018-07-03T10:04:38.480Z getting http://www.lanin.net/
2018-07-03T10:04:38.982Z Started Chrome: HeadlessChrome/67.0.3396.79
2018-07-03T10:05:08.511Z getting http://www.ih5.cn/
2018-07-03T10:05:09.133Z page timed out http://www.lanin.net/
2018-07-03T10:05:09.243Z got 504 in 30763ms for http://www.lanin.net/
2018-07-03T10:05:38.543Z getting http://www.ems.com.cn/
2018-07-03T10:05:38.575Z page timed out http://www.ih5.cn/
2018-07-03T10:05:42.950Z got 200 in 4407ms for http://www.ems.com.cn/
2018-07-03T10:05:43.112Z getting http://
2018-07-03T10:05:43.112Z invalid URL: http://
2018-07-03T10:05:43.112Z got 400 in 0ms for http://
2018-07-03T10:05:43.118Z getting http://
2018-07-03T10:05:43.118Z invalid URL: http://
2018-07-03T10:05:43.118Z got 400 in 0ms for http://
2018-07-03T10:05:43.123Z getting http://
2018-07-03T10:05:43.123Z invalid URL: http://
2018-07-03T10:05:43.124Z got 400 in 1ms for http://
2018-07-03T10:05:43.134Z getting http://www.kuwo.cn/

**Comment by thoop** [comment]
Hmm, it looks like Chrome crashed or something and the Prerender server wasn't aware that it crashed so it kept trying to send requests.

After restarting the Chrome server though, you can see that it connects to Chrome. It looks like the request to http://www.ems.com.cn/ worked fine since that took 4407ms to complete...so is it working correctly after it restarts itself? Did you take a look at the high CPU usage? Are you running Chrome with any custom flags?

**Comment by lican09** [comment]
There is no custom flags to use for the server. Maybe, the reason is that the Chrome server and prerender is running in docker, I can see the highly CPU loading and Chrome always restarting after few requests.

So, is there any advice ?

**Comment by thoop** [comment]
How high of CPU usage are you seeing? And how many minutes are you seeing in between the Chrome restarts? By default, we have Chrome try to restart itself every 10 minutes if there are no requests in flight.

I'm not sure if this would be due to docker or not, but we haven't run into this issue yet and we are not using docker.

**Comment by lican09** [comment]
According to my grep log file, I can see the chrome's frequent restarts.


2018-07-06T17:50:46.093Z Started Chrome: HeadlessChrome/67.0.3396.79
2018-07-06T17:51:28.147Z Started Chrome: HeadlessChrome/67.0.3396.79
2018-07-06T17:52:16.246Z Started Chrome: HeadlessChrome/67.0.3396.79
2018-07-06T17:53:25.411Z Started Chrome: HeadlessChrome/67.0.3396.79
2018-07-06T17:53:58.256Z Started Chrome: HeadlessChrome/67.0.3396.79
2018-07-06T17:54:19.559Z Started Chrome: HeadlessChrome/67.0.3396.79
2018-07-06T17:54:40.468Z Started Chrome: HeadlessChrome/67.0.3396.79
2018-07-06T17:54:58.698Z Started Chrome: HeadlessChrome/67.0.3396.79
2018-07-06T17:55:20.281Z Started Chrome: HeadlessChrome/67.0.3396.79
2018-07-06T17:55:46.257Z Started Chrome: HeadlessChrome/67.0.3396.79
2018-07-06T17:56:25.544Z Started Chrome: HeadlessChrome/67.0.3396.79
2018-07-06T17:57:12.047Z Started Chrome: HeadlessChrome/67.0.3396.79
2018-07-06T17:57:30.705Z Started Chrome: HeadlessChrome/67.0.3396.79
2018-07-06T17:58:34.133Z Started Chrome: HeadlessChrome/67.0.3396.79
2018-07-06T17:58:41.467Z Started Chrome: HeadlessChrome/67.0.3396.79
2018-07-06T17:58:57.251Z Started Chrome: HeadlessChrome/67.0.3396.79
2018-07-06T17:59:12.375Z Started Chrome: HeadlessChrome/67.0.3396.79
2018-07-06T17:59:29.916Z Started Chrome: HeadlessChrome/67.0.3396.79
2018-07-06T17:59:50.252Z Started Chrome: HeadlessChrome/67.0.3396.79
2018-07-06T18:00:56.297Z Started Chrome: HeadlessChrome/67.0.3396.79
2018-07-06T18:02:05.559Z Started Chrome: HeadlessChrome/67.0.3396.79
2018-07-06T18:02:22.588Z Started Chrome: HeadlessChrome/67.0.3396.79
2018-07-06T18:02:40.224Z Started Chrome: HeadlessChrome/67.0.3396.79

**Comment by lican09** [comment]
2018-07-11T09:57:31.583Z getting http://www.bailingjie.cn/
2018-07-11T09:57:31.586Z { Error: connect ECONNREFUSED 127.0.0.1:9222
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1158:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9222 }
2018-07-11T09:57:31.587Z got 504 in 4ms for http://www.bailingjie.cn/
2018-07-11T09:57:32.099Z getting http://www.leadong.com/
2018-07-11T09:57:32.102Z { Error: connect ECONNREFUSED 127.0.0.1:9222
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1158:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9222 }
2018-07-11T09:57:32.102Z got 504 in 3ms for http://www.leadong.com/
2018-07-11T09:57:32.617Z getting http://www.100yy.com/
2018-07-11T09:57:32.619Z { Error: connect ECONNREFUSED 127.0.0.1:9222
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1158:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9222 }
2018-07-11T09:57:32.619Z got 504 in 2ms for http://www.100yy.com/
2018-07-11T09:57:33.135Z getting http://www.yunos.com/
2018-07-11T09:57:33.142Z { Error: connect ECONNREFUSED 127.0.0.1:9222
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1158:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9222 }
2018-07-11T09:57:33.144Z got 504 in 8ms for http://www.yunos.com/
2018-07-11T09:57:33.657Z getting http://www.hongdezk.com/
2018-07-11T09:57:33.660Z { Error: connect ECONNREFUSED 127.0.0.1:9222
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1158:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9222 }
2018-07-11T09:57:33.661Z got 504 in 4ms for http://www.hongdezk.com/
2018-07-11T09:57:33.790Z capture screenshot timed out for http://www.gfedu.com/
2018-07-11T09:57:33.791Z got 504 in 30057ms for http://www.gfedu.com/
**2018-07-11T09:57:33.791Z error closing Chrome tab Error: not opened**
    at WebSocket.send (/code/node_modules/ws/lib/WebSocket.js:355:18)
    at Chrome.enqueueCommand (/code/node_modules/chrome-remote-interface/lib/chrome.js:124:16)
    at /code/node_modules/chrome-remote-interface/lib/chrome.js:86:28
    at new Promise (<anonymous>)
    at Chrome.send (/code/node_modules/chrome-remote-interface/lib/chrome.js:85:16)
    at Object.handler [as closeTarget] (/code/node_modules/chrome-remote-interface/lib/api.js:32:23)
    at Promise (/code/lib/browsers/chrome.js:148:22)
    at new Promise (<anonymous>)
    at Object.chrome.closeTab (/code/lib/browsers/chrome.js:146:9)
    at Object.server.finish (/code/lib/server.js:277:16)
2018-07-11T09:57:34.177Z getting http://www.5u5u5u5u.com/

**Comment by lican09** [comment]
I gave up to use docker, and resolved this problem.

**Comment by lican09** [comment]
Maby, I find the better way to this problem. Docker run with `--shm-size 1G` and that crashes not exists.
Detail: https://bugs.chromium.org/p/chromium/issues/detail?id=571394

**Comment by thoop** [comment]
Oh yeah? So everything looks good after giving it access to more RAM?

**Comment by lican09** [comment]
yeah

**Comment by estshy** [comment]
@thoop @lican09 Problem exists for chrome headless running on docker and can be solved be either setting --shm-size or starting chrome with flag --disable-dev-shm-usage. Second option is useful for AWS. More information can be found on https://developers.google.com/web/tools/puppeteer/troubleshooting

**Comment by thoop** [comment]
Thanks for the info!

**Comment by leducanhdodo** [comment]
> @thoop @lican09 Problem exists for chrome headless running on docker and can be solved be either setting --shm-size or starting chrome with flag --disable-dev-shm-usage. Second option is useful for AWS. More information can be found on https://developers.google.com/web/tools/puppeteer/troubleshooting

Thanks! It saved my day

**Comment by micktaiwan** [comment]
none of the solutions above works for me. :(
