### ISSUE TITLE
Got 404 after cache is cleared?

### ISSUE THREAD

**Issue by vIceBerg** [prerender/prerender#580]
HI!

I'm using a locally served prerender with memory cache.

I start the app, send a request with Postman using the url http://myserver:3001[THE_URL_I_WANT_TO_PRERENDER]

The first call works as expected within 2000ms. The second call wokds as expected within 0-50ms as the page is cached.

If I wait a little (3 minutes), when I request the same page I got a lot of errors.

`2019-04-09T16:37:41.806Z getting THE_URL_I_WANT_TO_PRERENDER
2019-04-09T16:37:41.806Z got 200 in 0ms for THE_URL_I_WANT_TO_PRERENDER
2019-04-09T16:37:43.399Z getting THE_URL_I_WANT_TO_PRERENDER
2019-04-09T16:37:43.399Z got 200 in 0ms for THE_URL_I_WANT_TO_PRERENDER
2019-04-09T16:38:47.423Z getting THE_URL_I_WANT_TO_PRERENDER
2019-04-09T16:38:47.476Z Error: unexpected server response (404)
    at ClientRequest._req.on (D:\Programs\TuxedoPrerender\node_modules\ws\lib\WebSocket.js:653:21)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:474:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at Socket.socketOnData (_http_client.js:363:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
2019-04-09T16:38:47.482Z got 504 in 59ms for THE_URL_I_WANT_TO_PRERENDER`

I configured the cache with those params:
CACHE_MAXSIZE= 2000
CACHE_TTL= 259200

I even saw this line in the console, but I can't reproduce it right now:
invalid URL: ws/v1/cluster/apps/new-application

What can I do to correct that?

Thanks

**Comment by thoop** [comment]
Thanks for reporting this. Can you confirm which in memory cache plugin you are using? And how you've added that to your prerender server? That way I can test with the same configuration and see what's going on here.

**Comment by vIceBerg** [comment]
HI!

 

I’m using 

const prerenderMemoryCache = require('prerender-memory-cache');

 

server.use(prerenderMemoryCache);

 

with 

set CACHE_TTL=259200

set CACHE_MAXSIZE=2000

**Comment by thoop** [comment]
I'm not able to reproduce this when I test locally. Here is what I see with those settings:
```
2019-04-10T20:33:25.922Z getting https://prerender.io/
2019-04-10T20:33:28.871Z warning: unable to set header: set-cookie
2019-04-10T20:33:28.879Z got 200 in 2957ms for https://prerender.io/
2019-04-10T20:33:36.776Z getting https://prerender.io/
2019-04-10T20:33:36.785Z got 200 in 8ms for https://prerender.io/
2019-04-10T20:36:08.587Z getting https://prerender.io/
2019-04-10T20:36:08.590Z got 200 in 3ms for https://prerender.io/
2019-04-10T20:37:39.086Z getting https://prerender.io/
2019-04-10T20:37:39.095Z got 200 in 9ms for https://prerender.io/
```

Are there any other changes that you've made there?
