### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: not opened

### ISSUE THREAD

**Issue by Nyoroon** [prerender/prerender#599]
```
node[3403]: (node:3403) UnhandledPromiseRejectionWarning: Error: not opened
node[3403]: at WebSocket.send (/opt/prerender/node_modules/ws/lib/WebSocket.js:359:18)
node[3403]: at Chrome.enqueueCommand (/opt/prerender/node_modules/chrome-remote-interface/lib/chrome.js:130:16)
node[3403]: at /opt/prerender/node_modules/chrome-remote-interface/lib/chrome.js:88:28
node[3403]: at new Promise (<anonymous>)
node[3403]: at Chrome.send (/opt/prerender/node_modules/chrome-remote-interface/lib/chrome.js:87:16)
node[3403]: at Object.handler [as continueInterceptedRequest] (/opt/prerender/node_modules/chrome-remote-interface/lib/api.js:32:23)
node[3403]: at Chrome.req.prerender.tab.Network.requestIntercepted (/opt/prerender/node_modules/prerender/lib/plugins/blockResources.js:62:30)
node[3403]: at Chrome.emit (events.js:198:13)
node[3403]: at Chrome.EventEmitter.emit (domain.js:448:20)
node[3403]: at Chrome.handleMessage (/opt/prerender/node_modules/chrome-remote-interface/lib/chrome.js:311:16)
node[3403]: (node:3403) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 352)
```

**Comment by vdt-mik** [comment]
I have the same problem.

**Comment by thoop** [comment]
This seems like Chrome couldn't start the remote debugging interface or it crashed? Please reopen with your version of Prerender and version of Chrome if you are still having these issues.
