### ISSUE TITLE
"finally is not a function" under onRequest

### ISSUE THREAD

**Issue by lukaszkoziara** [prerender/prerender#708]
After upgrading to the newest version (from old one 5.6.0) I encountered an issue with `finally` statement within `onRequest` definition https://github.com/prerender/prerender/blob/18efadbf61c140be1204bcf0e6f32d8f4a9f48bb/lib/server.js#L304

```
TypeError: this.firePluginEvent(...).then(...).then(...).then(...).then(...).then(...).then(...).then(...).then(...).then(...).then(...).catch(...).finally is not a function
    at Object.server.onRequest (/srv/prerender/lib/server.js:304:12)
    at Layer.handle [as handle_request] (/srv/prerender/node_modules/express/lib/router/layer.js:95:5)
    at next (/srv/prerender/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/srv/prerender/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/srv/prerender/node_modules/express/lib/router/layer.js:95:5)
    at /srv/prerender/node_modules/express/lib/router/index.js:281:22
    at param (/srv/prerender/node_modules/express/lib/router/index.js:354:14)
    at param (/srv/prerender/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/srv/prerender/node_modules/express/lib/router/index.js:410:3)
    at next (/srv/prerender/node_modules/express/lib/router/index.js:275:10)
```

Simply workaround is to change `finally` statement into `then` (as `then` after `catch` is behave the same like `finally`)

Is it maybe connected somehow with my local environment and Chrome version (`Started Chrome: HeadlessChrome/80.0.3987.116`)?

**Comment by larrymeng** [comment]
Same to me:
TypeError: this.firePluginEvent(...).then(...).then(...).then(...).then(...).then(...).then(...).then(...).then(...).then(...).then(...).catch(...).finally is not a function
    at Object.server.onRequest (/data/prerender_server/node_modules/prerender/lib/server.js:307:12)
    at Layer.handle [as handle_request] (/data/prerender_server/node_modules/express/lib/router/layer.js:95:5)
    at next (/data/prerender_server/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/data/prerender_server/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/data/prerender_server/node_modules/express/lib/router/layer.js:95:5)
    at /data/prerender_server/node_modules/express/lib/router/index.js:284:15
    at param (/data/prerender_server/node_modules/express/lib/router/index.js:365:14)
    at param (/data/prerender_server/node_modules/express/lib/router/index.js:376:14)
    at Function.process_params (/data/prerender_server/node_modules/express/lib/router/index.js:421:3)
    at next (/data/prerender_server/node_modules/express/lib/router/index.js:280:10)

**Comment by varrocs** [comment]
Finally needs nodejs version >= 10
