### ISSUE TITLE
Error: unexpected server response (404) and sometime getting 504 and restarting Chrome error

### ISSUE THREAD

**Issue by simranjeetsingh** [prerender/prerender#716]
Hey Guys,

Somehow our prerender middleware started giving errors
sometime it returns error 

27|PRERENDER_API  | 2021-11-17T14:42:01.514Z getting https://www.agfolks.com/product/quick-hitch-adapter
27|PRERENDER_API  | 2021-11-17T14:42:01.545Z Error: unexpected server response (404)
27|PRERENDER_API  |     at ClientRequest.<anonymous> (/home/missio/public_html/cms/api-prerender/node_modules/ws/lib/WebSocket.js:653:21)
27|PRERENDER_API  |     at ClientRequest.emit (events.js:400:28)
27|PRERENDER_API  |     at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
27|PRERENDER_API  |     at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)
27|PRERENDER_API  |     at Socket.socketOnData (_http_client.js:515:22)
27|PRERENDER_API  |     at Socket.emit (events.js:400:28)
27|PRERENDER_API  |     at addChunk (internal/streams/readable.js:293:12)
27|PRERENDER_API  |     at readableAddChunk (internal/streams/readable.js:267:9)
27|PRERENDER_API  |     at Socket.Readable.push (internal/streams/readable.js:206:10)
27|PRERENDER_API  |     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

and also
some times getting this

26|PRERENDER_API  | 2021-11-17T14:29:45.266Z got 504 in 34ms for https://www.agfolks.com/product/mini-pallet-fork-add-a-grapple
26|PRERENDER_API  | 2021-11-17T14:29:45.281Z Chrome connection closed... restarting Chrome
26|PRERENDER_API  | 2021-11-17T14:29:45.281Z Starting Chrome
26|PRERENDER_API  | 2021-11-17T14:29:45.791Z Started Chrome: HeadlessChrome/97.0.4692.20

Please help

**Comment by gorkemogut** [comment]
You may try using pm2 and starting it with: 
`pm2 start index.js --node-args="--max-old-space-size=4096"`

**Comment by gorkemogut** [comment]
I've fixed this issue by decreasing the restart period from 10 mins to 2 mins by setting `BROWSER_TRY_RESTART_PERIOD`
