### ISSUE TITLE
Timed out waiting for Chrome connection after Restarting Chrome

### ISSUE THREAD

**Issue by nijinekoyo** [prerender/prerender#761]
Running prerender in a docker container, after a period of time, all requests `Timed out waiting for Chrome connection` will appear. After observation, I found that most of them appear after `Restarting Chrome`. I try to set `BROWSER_TRY_RESTART_PERIOD` time This problem will appear faster after being shortened. It is speculated that the source of the problem is a problem with the steps to reset Chrome

Version: 
```
$ node server.js
2023-07-03T05:28:50.172Z Starting Prerender
2023-07-03T05:28:50.175Z Starting Chrome
2023-07-03T05:28:50.193Z Prerender server accepting requests on port 3000
2023-07-03T05:28:50.713Z Started Chrome: HeadlessChrome/114.0.5735.198
```

**Comment by nijinekoyo** [comment]
Full problem log, `BROWSER_TRY_RESTART_PERIOD` is 60000

```
$ node server.js
2023-07-03T05:38:04.987Z Starting Prerender
2023-07-03T05:38:04.989Z Starting Chrome
2023-07-03T05:38:04.997Z Prerender server accepting requests on port 3000
2023-07-03T05:38:05.517Z Started Chrome: HeadlessChrome/114.0.5735.198
2023-07-03T05:38:10.731Z getting https://kivo.wiki/data/character/42
2023-07-03T05:38:10.975Z Initial request to https://kivo.wiki/data/character/42
2023-07-03T05:38:11.595Z Initial response from https://kivo.wiki/data/character/42 with status code 200
2023-07-03T05:38:11.765Z Initial request finished https://kivo.wiki/data/character/42
2023-07-03T05:38:56.119Z got 200 in 45387ms for https://kivo.wiki/data/character/42
2023-07-03T05:39:00.140Z getting https://kivo.wiki/data/character/42
2023-07-03T05:39:00.724Z Initial request to https://kivo.wiki/data/character/42
2023-07-03T05:39:00.989Z Initial response from https://kivo.wiki/data/character/42 with status code 200
2023-07-03T05:39:01.054Z Initial request finished https://kivo.wiki/data/character/42
2023-07-03T05:39:42.916Z Restarting Chrome
2023-07-03T05:39:42.984Z got 200 in 42844ms for https://kivo.wiki/data/character/42
2023-07-03T05:39:47.578Z getting https://kivo.wiki/data/character/42
2023-07-03T05:40:07.627Z Timed out waiting for Chrome connection
2023-07-03T05:40:07.733Z got 504 in 20151ms for https://kivo.wiki/data/character/42
```

**Comment by AbbasHallal** [comment]
I am having the same issue and the only way to get rid of this is to restart the container

**Comment by nijinekoyo** [comment]
> @nijinekoyo I am having the same issue and the only way to get rid of this is to restart the container as for now

I'm currently doing the same thing, setting a super long reset chrome time, and then restarting the container regularly, but I always feel that this may cause problems: (

**Comment by AbbasHallal** [comment]
@nijinekoyo I followed this solution and it worked for me  https://github.com/prerender/prerender/issues/755
I reverted back this change. https://github.com/prerender/prerender/pull/748/files
Give it a try!

**Comment by nijinekoyo** [comment]
> @nijinekoyo I followed this solution and it worked for me #755 I reverted back this change. https://github.com/prerender/prerender/pull/748/files Give it a try!

This is useful, he does solve the problem caused by resetting chrome, but he will cause new errors, I'm not sure if he will have bad effects

```
2023-07-04T03:37:53.090Z Starting Prerender
2023-07-04T03:37:53.092Z Starting Chrome
2023-07-04T03:37:53.104Z Prerender server accepting requests on port 3000
2023-07-04T03:37:53.624Z Started Chrome: HeadlessChrome/114.0.5735.198
2023-07-04T03:37:56.557Z getting https://kivo.wiki/data/character/42
2023-07-04T03:37:56.807Z Initial request to https://kivo.wiki/data/character/42
2023-07-04T03:37:57.430Z Initial response from https://kivo.wiki/data/character/42 with status code 200
2023-07-04T03:37:57.452Z Initial request finished https://kivo.wiki/data/character/42
2023-07-04T03:38:35.817Z Restarting Chrome
2023-07-04T03:38:35.832Z got 200 in 39275ms for https://kivo.wiki/data/character/42
2023-07-04T03:38:35.843Z error closing Chrome tab Error: WebSocket is not open: readyState 3 (CLOSED)
    at sendAfterClose (/prerender/node_modules/ws/lib/websocket.js:988:17)
    at WebSocket.send (/prerender/node_modules/ws/lib/websocket.js:405:7)
    at Chrome._enqueueCommand (/prerender/node_modules/chrome-remote-interface/lib/chrome.js:286:18)
    at /prerender/node_modules/chrome-remote-interface/lib/chrome.js:88:22
    at new Promise (<anonymous>)
    at Chrome.send (/prerender/node_modules/chrome-remote-interface/lib/chrome.js:87:20)
    at Object.handler [as disposeBrowserContext] (/prerender/node_modules/chrome-remote-interface/lib/api.js:32:23)
    at /prerender/lib/browsers/chrome.js:186:31
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-07-04T03:38:35.920Z Chrome connection closed... restarting Chrome
2023-07-04T03:38:35.920Z Starting Chrome
2023-07-04T03:38:36.434Z Started Chrome: HeadlessChrome/114.0.5735.198
```

**Comment by gorkemogut** [comment]
I've fixed the timeout issue by calling `this.startPrerender();` at the end of `server.restartBrowser` function in lib/server.js:143

which will be like:

`
server.restartBrowser = function () {
	this.isBrowserConnected = false;
	util.log(`Restarting ${this.browser.name}`);
	this.browser.kill();
	this.startPrerender();
};
`

**Comment by gorkemogut** [comment]
> I am trying a workaround by adding the code below:
> 
> ```js
> this.startPrerender();
> ```
> 
> at the end of `server.restartBrowser` function in `./lib/server.js:143` to force the restart.
> 
> which will be like:
> 
> ```js
> server.restartBrowser = function () {
> 	this.isBrowserConnected = false;
> 	util.log(`Restarting ${this.browser.name}`);
> 	this.browser.kill();
> 	this.startPrerender(); //<--- This will be added
> };
> ```
> 
> I believe there is an issue with latest chrome versions which causes error on prerender to listen `chromeChild.on('close', callback)` event and that locks the whole process. That's why triggering the start function without listening `close` event seems to solve it.
> 
> I am not sure if it will cause any memory leak but it is working for now, at least.

Disable `browserForceRestart` plugin also which relies on `close` event and causes timeout error.

**Comment by gorkemogut** [comment]
> I am trying a workaround by adding the code below:
> 
> ```js
> this.startPrerender();
> ```
> 
> at the end of `server.restartBrowser` function in `./lib/server.js:143` to force the restart.
> 
> which will be like:
> 
> ```js
> server.restartBrowser = function () {
> 	this.isBrowserConnected = false;
> 	util.log(`Restarting ${this.browser.name}`);
> 	this.browser.kill();
> 	this.startPrerender(); //<--- This will be added
> };
> ```
> 
> I believe there is an issue with latest chrome versions which causes error on prerender to listen `chromeChild.on('close', callback)` event and that locks the whole process. That's why triggering the start function without listening `close` event seems to solve it.
> 
> I am not sure if it will cause any memory leak but it is working for now, at least.
> 
> Disable `browserForceRestart` plugin also from server.js on root which relies on close event and probably causing error.
> 
> ```js
> // server.use(prerender.browserForceRestart());
> ```
> 
> **UPDATE:**
> 
> No chance :( Memory leak as I guessed. Trying to install older Chrome version that I got from the container @jirikrepl shared.

None of the approaches I tried have worked yet. Even tried chromium versions instead of chrome-stable but no chance. Considering permission issues now.

**Comment by breakiboy** [comment]
Hi guys,

I faced the same problem. I fixed It quick and dirty 👯 

create a new file e.q monitor.js and copy paste this:

const { spawn } = require('child_process');

let yourCommand;

function startAndMonitorProcess() {
  if (yourCommand) {
    yourCommand.stdout.removeAllListeners('data');
    yourCommand.stderr.removeAllListeners('data');
    yourCommand.kill();
  }

  yourCommand = spawn('node', ['server.js']);

  yourCommand.stdout.on('data', (data) => {
    console.log(`stdout: ${data}`);
    if (data.includes('Timed out waiting for Chrome connection')) {
      console.log("Error detected! Restarting...");
      startAndMonitorProcess();
    }
  });

  yourCommand.stderr.on('data', (data) => {
    console.error(`stderr: ${data}`);
  });

  yourCommand.on('close', (code) => {
    console.log(`child process exited with code ${code}`);
  });
}

startAndMonitorProcess();

this will check the output of server.js if the problem is listed in the console - this script will kill the instance and create a new server.js instance and begins from begin to listen the output.

**Comment by gorkemogut** [comment]
> Hi guys,
> 
> I faced the same problem. I have for this problem a quick and dirty workaround.👯
> 
> create a new file e.q monitor.js and copy paste this:
> 
> const { spawn } = require('child_process');
> 
> let yourCommand;
> 
> function startAndMonitorProcess() { if (yourCommand) { yourCommand.stdout.removeAllListeners('data'); yourCommand.stderr.removeAllListeners('data'); yourCommand.kill(); }
> 
> yourCommand = spawn('node', ['server.js']);
> 
> yourCommand.stdout.on('data', (data) => { console.log(`stdout: ${data}`); if (data.includes('Timed out waiting for Chrome connection')) { console.log("Error detected! Restarting..."); startAndMonitorProcess(); } });
> 
> yourCommand.stderr.on('data', (data) => { console.error(`stderr: ${data}`); });
> 
> yourCommand.on('close', (code) => { console.log(`child process exited with code ${code}`); }); }
> 
> startAndMonitorProcess();
> 
> this will check the output of server.js if the problem is listed in the console - this script will kill the instance and create a new server.js instance and begins from begin to listen the output.

Great I've made some additions to put some pm2 magic in it. you can save it as pm2_monitor.js and run it also by using pm2 like `pm2 start pm2_monitor.js` 

```javascript
const { spawn } = require('child_process');
const pm2 = require('pm2')

let yourCommand;
pm2.connect(function (err) {
    if (err) {
        console.error(err)
        process.exit(2)
    }
    pm2.start({
        script: 'server.js',
        name: 'server',
        instances: 7
    }, function (err, apps) {
        if (err) {
            console.error(err)
            return pm2.disconnect()
        }
        yourCommand = spawn('pm2', ['log']);
        yourCommand.stdout.on('data', (data) => {
            if (data.includes('page timed out') || data.includes('parse html timed out') || data.includes('Timed out waiting for')) {
                console.log("Error detected! Restarting...");
                pm2.restart('server', (err, proc) => {
                    if (err) {
                        console.log(err);
                        return pm2.disconnect()
                    }
                });
            }
        });
    })
})
```

**Comment by gorkemogut** [comment]
We should find a proper solution for the main issue btw. I am still investigating.

**Comment by captainjackrana** [comment]
Same issue.. confirmed on Mac M2 with Chrome 114

**Comment by bilipp** [comment]
Is there any update for this? Facing the same issue

**Comment by sovietsolider** [comment]
Facing the same with ubuntu 22.04

**Comment by kruff** [comment]
The same Debian 10 + Chrome 120

**Comment by turicas** [comment]
I'm having the same problem on my deployment. The way I partially solved was to run 4 processes (4 containers, each one running `node server.js`) and reverse proxy a nginx server to them, so if one fails nginx will forward to request to another process.

I'm not sure if it's related to browser restarting (the restart plugin is enabled) but saw this on container's stdout:

```
 /app/node_modules/ws/lib/websocket.js:988
     const err = new Error(
                 ^

 Error: WebSocket is not open: readyState 2 (CLOSING)
     at sendAfterClose (/app/node_modules/ws/lib/websocket.js:988:17)
     at WebSocket.send (/app/node_modules/ws/lib/websocket.js:405:7)
     at Chrome._enqueueCommand (/app/node_modules/chrome-remote-interface/lib/chrome.js:286:18)
     at /app/node_modules/chrome-remote-interface/lib/chrome.js:88:22
     at new Promise (<anonymous>)
     at Chrome.send (/app/node_modules/chrome-remote-interface/lib/chrome.js:87:20)
     at Object.handler [as continueInterceptedRequest] (/app/node_modules/chrome-remote-interface/lib/api.js:32:23)
     at Chrome.<anonymous> (/app/node_modules/prerender/lib/plugins/blockResources.js:62:30)
     at Chrome.emit (node:events:519:28)
     at Chrome._handleMessage (/app/node_modules/chrome-remote-interface/lib/chrome.js:272:18)

 Node.js v21.6.2
```

**Comment by 1u** [comment]
Same here: `Timed out waiting for Chrome connection`


Chromium 135, Debian 12, prerender in docker container

chrome is restarting automatically:

`docker logs`  
 
![Image](https://github.com/user-attachments/assets/5f905f68-6fc9-4b9c-9389-4bc837895d7a)

**Comment by kkk-kppi** [comment]
As you can see, I have also encountered this problem; Similar to the question from the author, it has appeared more than 500 times after `Restarting Chrome`.  I will continue to pay attention to this issue

**Comment by dawangong** [comment]
It seems that, up to today, this issue still hasn't been resolved. I've tried disabling many non-essential features of Chrome, and the memory usage is currently very low. I hope everything will be fine now. But why does the restart fail? Is it due to memory overflow or a problem with the reset steps? I'll keep an eye on it. Will anyone be able to find the cause?

**Comment by pimverlangen** [comment]
Any updates on this matter? We also seem to encounter this issue, although after some time Chrome seems to be restarted and the 504s are absent for a while (until the next restart happens).
