### ISSUE TITLE
Syntax Error when using extraChromeFlags option

### ISSUE THREAD

**Issue by yash-maurya** [prerender/prerender#781]
Hi,
When attempting to use the `extraChromeFlags` option in the library, the server throws error `TypeError: Assignment to constant variable.`

**Code:**
```
const prerender = require('prerender');
const server = prerender({extraChromeFlags:['--no-sandbox']});
server.start();
```
**Console:**
> 2024-04-18T16:55:30.460Z Starting Prerender
2024-04-18T16:55:30.463Z Starting Chrome
2024-04-18T16:55:30.465Z Prerender server accepting requests on port 3000
2024-04-18T16:55:30.466Z TypeError: Assignment to constant variable.
    at /Users/User/Desktop/Test/pre/node_modules/prerender/lib/browsers/chrome.js:43:51
    at new Promise (<anonymous>)
    at Object.chrome.spawn (/Users/User/Desktop/Test/pre/node_modules/prerender/lib/browsers/chrome.js:26:9)
    at Object.server.spawnBrowser (/Users/User/Desktop/Test/pre/node_modules/prerender/lib/server.js:130:22)
    at /Users/User/Desktop/Test/pre/node_modules/prerender/lib/server.js:81:8
    at new Promise (<anonymous>)
    at Object.server.startPrerender (/Users/User/Desktop/Test/pre/node_modules/prerender/lib/server.js:80:9)
    at Object.server.start (/Users/User/Desktop/Test/pre/node_modules/prerender/lib/server.js:60:7)
    at Object.<anonymous> (/Users/User/Desktop/Test/pre/server.js:3:8)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
2024-04-18T16:55:30.471Z Failed to start and/or connect to Chrome. Please make sure Chrome is running
2024-04-18T16:55:30.471Z Stopping Chrome

**Comment by avelinesg** [comment]
Fixed by https://github.com/prerender/prerender/pull/783 and released `5.20.4`
